# Netlify 배포 설정
[build]
  base = "frontend"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://your-backend-url.run.app/api"

# Next.js 플러그인
[[plugins]]
  package = "@netlify/plugin-nextjs"
