# Netlify 배포 설정
[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://your-backend-url.run.app/api"
