[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_API_URL = "https://vibescan.kr/api"
  NEXT_PUBLIC_BACKEND_URL = "https://vibescan.kr/api"
  NEXT_PUBLIC_TOSS_CLIENT_KEY = "live_ck_Z1aOwX7K8mvgmPmaRp9B3yQxzvNP"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
